name: Publish NPM Package

on:
  release:
    types: [created]
  workflow_dispatch:

#jobs:
#  build-and-push-image:
#    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/yarn-publish-pkg.yml@main
#    secrets:
#      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#

jobs:
  publish-github-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: yarn install
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
