name: Publish NPM Package

on:
  release:
    types: [ created ]
  workflow_dispatch:

jobs:
  build-and-push-image:
    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/yarn-publish-pkg.yml@main
