name: Publish NPM Package

on:
  release:
    types: [created]
  workflow_dispatch:

#jobs:
#  build-and-push-image:
#    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/yarn-publish-pkg.yml@main
#    secrets:
#      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#

jobs:
  publish-github-registry:
    runs-on: cx-public-ubuntu-x64
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3.9.1
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/
          always-auth: true
      - run: yarn install
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
