name: Security Scans

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  security:
    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/security-scans.yml@v1
    secrets: inherit
    with:
      run_bearer_scan: false
