on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  security:
    uses: MAD-Goat-Project/github-actions-workflows/.github/workflows/security-scans.yml@v1
    secrets: inherit
